name: aeson-match-qq
version: 1.7.0
synopsis: Declarative JSON matchers.
description: See README.markdown
category: Web
maintainer: matvey.aksenov@gmail.com
copyright: Matvey Aksenov 2022
license: BSD2
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown
github: supki/aeson-match-qq
tested-with:
  - GHC==9.6.5
  - GHC==9.8.2

default-extensions:
  - ImportQualifiedPost

dependencies:
  - base >= 4.14 && < 5

library:
  dependencies:
    - aeson
    - attoparsec
    - attoparsec-aeson
    - bytestring
    - case-insensitive
    - containers
    - either
    - haskell-src-meta
    - pretty
    - scientific
    - template-haskell
    - text
    - unordered-containers
    - vector
  source-dirs:
    src
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Wno-incomplete-uni-patterns
    # - -Werror

tests:
  spec:
    build-tools:
      - hspec-discover
    dependencies:
      - aeson
      - aeson-qq
      - aeson-match-qq
      - hspec
      - unordered-containers
    source-dirs:
      test
    main:
      Spec.hs
    ghc-options:
      - -Wall
      - -Wno-incomplete-uni-patterns
      # - -Werror
      - -threaded
      - -with-rtsopts=-N
